import { Book, Category } from './types';

export const DEFAULT_BOOK_COVER =
  'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=600&auto=format&fit=crop';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cuet-pg',
    title: 'CUET PG',
    seolsug: 'cuet-pg',
    seo_description: 'Comprehensive study material, question banks, and mock tests for CUET PG exams.',
  },
  {
    id: 'upsc-civil-services',
    title: 'UPSC Civil Services',
    seolsug: 'upsc-civil-services',
    seo_description: 'Prelims, Mains, CSAT and General Studies previous year question banks and guides.',
  },
  {
    id: 'ssc-cgl-chsl',
    title: 'SSC Exams',
    seolsug: 'ssc-cgl-chsl',
    seo_description: 'SSC CGL, CHSL, MTS quantitative aptitude and general awareness study kits.',
  },
  {
    id: 'banking-ibps-sbi',
    title: 'Banking & Insurance',
    seolsug: 'banking-ibps-sbi',
    seo_description: 'IBPS PO, Clerk, SBI and RBI exam preparation guides and practice test series.',
  },
  {
    id: 'state-psc',
    title: 'State PSC Exams',
    seolsug: 'state-psc',
    seo_description: 'State public service commission previous year papers and regional syllabus guides.',
  },
  {
    id: 'engineering-gate',
    title: 'Engineering & GATE',
    seolsug: 'engineering-gate',
    seo_description: 'GATE, ESE and technical exam chapter-wise solved objective questions and reference notes.',
  },
];

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'cuet-pg-agribusiness-management',
    title: 'CUET PG Agribusiness Management Question Bank',
    slug: 'cuet-pg-agribusiness-management',
    seoslug: 'cuet-pg-agribusiness-management',
    seo_description: 'Complete syllabus coverage, chapter-wise MCQs, and solved mock tests for CUET PG Agribusiness entrance exam.',
    full_description: 'This comprehensive guidebook provides in-depth coverage of agribusiness principles, agricultural economics, supply chain management, farm management, and marketing strategies specifically mapped to the CUET PG exam syllabus. Contains over 1,500 practice MCQs with detailed explanations.',
    seoDescription: 'Complete syllabus coverage, chapter-wise MCQs, and solved mock tests for CUET PG Agribusiness entrance exam.',
    fullDescription: 'This comprehensive guidebook provides in-depth coverage of agribusiness principles, agricultural economics, supply chain management, farm management, and marketing strategies specifically mapped to the CUET PG exam syllabus. Contains over 1,500 practice MCQs with detailed explanations.',
    category: 'CUET PG',
    categorySlug: 'cuet-pg',
    tags: ['featured', 'bestseller', 'CUET PG', 'Agribusiness', 'Question Bank'],
    isActive: true,
    buy_price: 149,
    list_price: 399,
    pdf_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfStoragePath: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hasFullPdf: true,
    cover: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=600&auto=format&fit=crop',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=600&auto=format&fit=crop',
    sample_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    sampleUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    rating: 4.8,
    rating_count: 1420,
    author: 'Mocktime Publication',
    publisher: 'Exam Kart Books',
    publication: 'Exam Kart Books',
    published_date: '2026',
    isbn: '978-93-89021-44-1',
    pages: 280,
    language: 'English',
    type: 'Question Bank PDF',
    file_size: '14.2 MB',
    topics: ['Agribusiness Fundamentals', 'Agricultural Economics', 'Marketing & Finance', 'Mock Test Papers'],
    reviews: [
      {
        id: 'rev-1',
        user: 'Vikram Sharma',
        rating: 5,
        date: '14 February 2026',
        comment: 'Extremely well structured. Helped me clear the entrance with high percentile.',
      },
    ],
  },
  {
    id: 'cuet-pg-agama-sanskrit',
    title: 'CUET PG Agama and Sanskrit Study Guide',
    slug: 'cuet-pg-agama-sanskrit',
    seoslug: 'cuet-pg-agama-sanskrit',
    seo_description: 'Master Sanskrit grammar, Agama literature, and Vedic studies for CUET PG entrance examination.',
    full_description: 'An authoritative study companion covering classical Sanskrit literature, Agama scriptures, Vyakarana, and Darshana. Contains topic-wise previous year question analysis and practice exercises.',
    seoDescription: 'Master Sanskrit grammar, Agama literature, and Vedic studies for CUET PG entrance examination.',
    fullDescription: 'An authoritative study companion covering classical Sanskrit literature, Agama scriptures, Vyakarana, and Darshana. Contains topic-wise previous year question analysis and practice exercises.',
    category: 'CUET PG',
    categorySlug: 'cuet-pg',
    tags: ['featured', 'CUET PG', 'Sanskrit', 'Agama'],
    isActive: true,
    buy_price: 129,
    list_price: 349,
    pdf_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfStoragePath: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hasFullPdf: true,
    cover: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=600&auto=format&fit=crop',
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=600&auto=format&fit=crop',
    sample_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    sampleUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    rating: 4.7,
    rating_count: 890,
    author: 'Dr. R. K. Shastri',
    publisher: 'Exam Kart Books',
    publication: 'Exam Kart Books',
    published_date: '2026',
    isbn: '978-93-89021-55-7',
    pages: 240,
    language: 'Hindi & Sanskrit',
    type: 'E-Book PDF',
    file_size: '11.8 MB',
    topics: ['Sanskrit Grammar', 'Agama Texts', 'Darshana & Philosophy', 'Solved Papers'],
    reviews: [],
  },
  {
    id: 'upsc-general-studies-prelims-handbook',
    title: 'UPSC General Studies Paper-I Master Handbook',
    slug: 'upsc-general-studies-prelims-handbook',
    seoslug: 'upsc-general-studies-prelims-handbook',
    seo_description: 'Concise high-yield revision notes for Indian Polity, Modern History, Geography, Environment, and Economy.',
    full_description: 'Designed by top civil services mentors, this handbook distills complex concepts into high-retention bullet points, mind maps, and summary charts for quick Prelims revision.',
    seoDescription: 'Concise high-yield revision notes for Indian Polity, Modern History, Geography, Environment, and Economy.',
    fullDescription: 'Designed by top civil services mentors, this handbook distills complex concepts into high-retention bullet points, mind maps, and summary charts for quick Prelims revision.',
    category: 'UPSC Civil Services',
    categorySlug: 'upsc-civil-services',
    tags: ['bestseller', 'featured', 'UPSC', 'General Studies', 'Prelims'],
    isActive: true,
    buy_price: 199,
    list_price: 599,
    pdf_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfStoragePath: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hasFullPdf: true,
    cover: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=600&auto=format&fit=crop',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=600&auto=format&fit=crop',
    sample_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    sampleUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    rating: 4.9,
    rating_count: 3200,
    author: 'Civil Services Editorial Board',
    publisher: 'BooksCircle Academic',
    publication: 'BooksCircle Academic',
    published_date: '2026',
    isbn: '978-93-89021-99-1',
    pages: 410,
    language: 'English',
    type: 'Handbook PDF',
    file_size: '22.5 MB',
    topics: ['Indian Polity & Governance', 'Modern Indian History', 'Physical & Indian Geography', 'Environment & Ecology'],
    reviews: [],
  },
  {
    id: 'ssc-cgl-quantitative-aptitude-speed-maths',
    title: 'SSC CGL Quantitative Aptitude & Speed Maths',
    slug: 'ssc-cgl-quantitative-aptitude-speed-maths',
    seoslug: 'ssc-cgl-quantitative-aptitude-speed-maths',
    seo_description: 'Shortcut tricks, formula sheets, and 2000+ solved practice problems for SSC CGL Tier 1 & Tier 2.',
    full_description: 'Master arithmetic, advanced geometry, trigonometry, algebra, and data interpretation with time-saving shortcut methods and chapter-wise previous year question analysis.',
    seoDescription: 'Shortcut tricks, formula sheets, and 2000+ solved practice problems for SSC CGL Tier 1 & Tier 2.',
    fullDescription: 'Master arithmetic, advanced geometry, trigonometry, algebra, and data interpretation with time-saving shortcut methods and chapter-wise previous year question analysis.',
    category: 'SSC Exams',
    categorySlug: 'ssc-cgl-chsl',
    tags: ['bestseller', 'SSC', 'Quantitative Aptitude', 'Speed Maths'],
    isActive: true,
    buy_price: 149,
    list_price: 449,
    pdf_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfStoragePath: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hasFullPdf: true,
    cover: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=600&auto=format&fit=crop',
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=600&auto=format&fit=crop',
    sample_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    sampleUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    rating: 4.8,
    rating_count: 2150,
    author: 'A. K. Aggarwal',
    publisher: 'Exam Kart Books',
    publication: 'Exam Kart Books',
    published_date: '2026',
    isbn: '978-93-89021-33-5',
    pages: 350,
    language: 'English',
    type: 'Practice Ebook',
    file_size: '18.4 MB',
    topics: ['Percentage & Profit-Loss', 'Geometry & Mensuration', 'Algebra & Trigonometry', 'Data Interpretation'],
    reviews: [],
  },
  {
    id: 'banking-ibps-po-reasoning-ability',
    title: 'IBPS PO & SBI PO Complete Reasoning Ability',
    slug: 'banking-ibps-po-reasoning-ability',
    seoslug: 'banking-ibps-po-reasoning-ability',
    seo_description: 'Master puzzles, seating arrangements, critical reasoning, and input-output for Banking PO exams.',
    full_description: 'High-level puzzle cracking strategies, blood relations, syllogisms, coded inequalities, and machine input-output questions designed for the latest IBPS PO and SBI PO pattern.',
    seoDescription: 'Master puzzles, seating arrangements, critical reasoning, and input-output for Banking PO exams.',
    fullDescription: 'High-level puzzle cracking strategies, blood relations, syllogisms, coded inequalities, and machine input-output questions designed for the latest IBPS PO and SBI PO pattern.',
    category: 'Banking & Insurance',
    categorySlug: 'banking-ibps-sbi',
    tags: ['featured', 'Banking', 'IBPS PO', 'Reasoning'],
    isActive: true,
    buy_price: 139,
    list_price: 399,
    pdf_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfStoragePath: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hasFullPdf: true,
    cover: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=600&auto=format&fit=crop',
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=600&auto=format&fit=crop',
    sample_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    sampleUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    rating: 4.7,
    rating_count: 1680,
    author: 'Priya Mukherjee',
    publisher: 'BooksCircle Academic',
    publication: 'BooksCircle Academic',
    published_date: '2026',
    isbn: '978-93-89021-77-9',
    pages: 310,
    language: 'English',
    type: 'Guidebook PDF',
    file_size: '15.6 MB',
    topics: ['Floor & Box Puzzles', 'Circular & Linear Seating', 'Critical Reasoning', 'Data Sufficiency'],
    reviews: [],
  },
  {
    id: 'gate-computer-science-core-handbook',
    title: 'GATE Computer Science & IT Complete Core Handbook',
    slug: 'gate-computer-science-core-handbook',
    seoslug: 'gate-computer-science-core-handbook',
    seo_description: 'Data structures, algorithms, operating systems, DBMS, and theory of computation summarized notes.',
    full_description: 'Essential formula sheets, standard algorithmic complexity tables, operating system memory management notes, and normalization guides tailored for GATE CS aspirants.',
    seoDescription: 'Data structures, algorithms, operating systems, DBMS, and theory of computation summarized notes.',
    fullDescription: 'Essential formula sheets, standard algorithmic complexity tables, operating system memory management notes, and normalization guides tailored for GATE CS aspirants.',
    category: 'Engineering & GATE',
    categorySlug: 'engineering-gate',
    tags: ['GATE', 'Computer Science', 'Engineering'],
    isActive: true,
    buy_price: 179,
    list_price: 499,
    pdf_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdf_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    pdfStoragePath: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    hasFullPdf: true,
    cover: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=600&auto=format&fit=crop',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=600&auto=format&fit=crop',
    sample_file: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    sampleUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    rating: 4.9,
    rating_count: 1940,
    author: 'Prof. S. N. Roy',
    publisher: 'BooksCircle Technical Press',
    publication: 'BooksCircle Technical Press',
    published_date: '2026',
    isbn: '978-93-89021-12-0',
    pages: 390,
    language: 'English',
    type: 'Handbook PDF',
    file_size: '19.1 MB',
    topics: ['Algorithms & Data Structures', 'Operating Systems', 'DBMS & SQL', 'Computer Networks'],
    reviews: [],
  },
];
